name:                busbroker
version:             0.1.0.0
github:              "voneiden/busbroker"
license:             MIT
author:              "Matti Eiden"
maintainer:          "snaipperi@gmail.com"
copyright:           "2020-2021 Matti Eiden"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/voneiden/busmaster#readme>

dependencies:
- base >= 4.9 && < 5
- containers
- stm
- stm-chans
- split
- network >= 3.1.2.0
- bytestring
- utf8-string
- tomland
- parsec
- timeit
- scotty
- aeson
- text
- time
- wai-cors


library:
  source-dirs:
  - src

executables:
  busmaster2000-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    #- -threaded
    - -rtsopts
    - -O2
    #- -fprof-auto
    #- '"-with-rtsopts=-N"'
    #- '"-with-rtsopts=-N4 -Iw60 -h"'
    - '"-with-rtsopts=-Iw60 -h"'
    # Try -Iw60 not available yet and sequential garbage collection
    dependencies:
    - busbroker

tests:
  busmaster2000-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - busbroker
